name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up pyenv
      run: |
        curl https://pyenv.run | bash
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init - bash)"' >> $GITHUB_ENV
        echo 'eval "$(pyenv virtualenv-init -)"' >> $GITHUB_ENV
    - name: Install Python ${{ matrix.python-version }}
      run: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init - bash)"
        eval "$(pyenv virtualenv-init -)"
        pyenv install -s ${{ matrix.python-version }}
        pyenv local ${{ matrix.python-version }}
        pip install -U pip
        pip install -r requirements.txt
        pip install pylint
    - name: Check for errors
      run: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init - bash)"
        eval "$(pyenv virtualenv-init -)"
        pyenv local ${{ matrix.python-version }}
        pylint . --recursive=y -j0 --max-line-length=127 --load-plugins=pylint.extensions.mccabe --max-complexity=50 --reports=y --disable=C0114,C0115,C0116,C0301,E0213,E1101,R0902,R0903,R0912,R0914,R0915
    - name: Check for other stuff
      run: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv virtualenv-init -)"
        pyenv local ${{ matrix.python-version }}
        pylint . --recursive=y -j0 --exit-zero --max-line-length=127 --load-plugins=pylint.extensions.mccabe --max-complexity=50 --reports=y --disable=all --enable=C0114,C0115,C0116
